### ISSUE TITLE
can `vscodemacros.macroFilePath`  config  supports `{workspaceRoot}/.vscode/macro.js`?

### ISSUE THREAD

**Issue by chen19901225** [exceedsystem/vscode-macros#3]

**Comment by exceedsystem** [comment]
Thanks for your advice.
I think it's possible and I'll just think about it.

**Comment by exceedsystem** [comment]
@chen19901225
If possible, please give me an additional information(for example, brief use case) for this request.
Best regards.

**Comment by exceedsystem** [comment]
I am currently testing a version that supports Multi-root, Workspace(Folders), and environment variables. Please wait a little longer.

**Comment by exceedsystem** [comment]
@chen19901225 
Version 1.3.0 has been released with support for  multi-root, workspace and workspace folders.

https://code.visualstudio.com/docs/getstarted/settings
https://code.visualstudio.com/docs/editor/multi-root-workspaces
