### ISSUE TITLE
allow env variables in path

### ISSUE THREAD

**Issue by rcx1** [exceedsystem/vscode-macros#5]
At the moment it is impossible to have path like '%APPDATA%/myvsmacros/macros.js'

Possible solution:
```
    if (macroModPath.indexOf('%') >= 0) {
        for (let key in process.env) {
            if (macroModPath.indexOf('%') >= 0) {
                macroModPath = macroModPath.replace('%' + key + '%', process.env[key])
            } else {
                break;
            }
        }
    }
```

**Comment by exceedsystem** [comment]
I am currently testing a version that supports Multi-root, Workspace(Folders), and environment variables. Please wait a little longer.

**Comment by exceedsystem** [comment]
@rcx1 
Version 1.3.0 has been released, which allows environment variables to be used in macro path.
